Repository openshift-knative/knative-kafka-operator, pull requests merged in 2019-10, with the labels that each got.

#33 Updating eventing-contrib kafka operator
  deploy/olm-catalog/knative-kafka-operator/0.9.0/eventing_v1alpha1_knativeeventingkafka_crd.yaml
  deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml
  deploy/olm-catalog/knative-kafka-operator/knative-kafka-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-eventing-contrib-kafka-v0.8.2.yaml
  deploy/resources/knative-eventing-kafka-contrib-v0.9.0.yaml
  deploy/resources/knative-eventing-kafka-cpp-v0.8.2.yaml
  pkg/controller/knativeeventingkafka/knativeeventingkafka_controller.go
  version/version.go
Labels: do-not-merge/hold, size/XXL

#34 Change kafka deploy resources
  deploy/resources/kafka-channel-v0.9.0.yaml
  deploy/resources/kafka-source-v0.9.0.yaml
  deploy/resources/knative-eventing-kafka-contrib-v0.9.0.yaml
Labels: size/XXL

#35 Adding override for quay.io images for 0.9.0
  deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml
Labels: size/XS

#36 Updates for openshift 4.2 OLM
  README.md
  deploy/olm-catalog/knative-kafka-operator/0.9.0/knative-kafka-operator.v0.9.0.clusterserviceversion.yaml
Labels: lgtm, size/S

#37 Add OWNERS file for openshift-bot
  OWNERS
Labels: lgtm, size/S

#38 align image w/ serving
  build/Dockerfile
Labels: approved, lgtm, size/XS
