Repository openshift-knative/knative-kafka-operator, pull requests merged in 2020-10, with the labels that each got.

#69 0.17 last release
  deploy/olm-catalog/knative-kafka-operator/0.17.1/eventing_v1alpha1_knativeeventingkafka_crd.yaml
  deploy/olm-catalog/knative-kafka-operator/0.17.1/knative-kafka-operator.v0.17.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-kafka-operator/knative-kafka-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/knative-eventing-kafka-contrib-v0.17.1.yaml
  version/version.go
Labels: approved

#70 Ok, we are now more mature...
  pkg/controller/knativeeventingkafka/knativeeventingkafka_controller.go
Labels: approved, lgtm

#71 Get the fix for https://github.com/knative/eventing-contrib/issues/1554
  deploy/resources/knative-eventing-kafka-contrib-v0.17.1.yaml
Labels: approved, do-not-merge/hold, lgtm
