Repository openshift-knative/knative-kafka-operator, pull requests merged in 2020-03, with the labels that each got.

#49 Removing myself from approvers/reviewers
  OWNERS
Labels: approved, size/XS

#51 updating to RHEL 8
  build/Dockerfile
Labels: lgtm, size/XS

#52 hiding CRDs
  deploy/olm-catalog/knative-kafka-operator/0.12.1/knative-kafka-operator.v0.12.1.clusterserviceversion.yaml
Labels: approved

#54 Prep 0.13
  deploy/olm-catalog/knative-kafka-operator/0.13.2/eventing_v1alpha1_knativeeventingkafka_crd.yaml
  deploy/olm-catalog/knative-kafka-operator/0.13.2/knative-kafka-operator.v0.13.2.clusterserviceversion.yaml
  deploy/olm-catalog/knative-kafka-operator/knative-kafka-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/kafka-channel-v0.12.1.yaml
  deploy/resources/kafka-source-v0.12.1.yaml
  deploy/resources/knative-eventing-kafka-contrib-v0.13.2.yaml
  deploy/resources/networkpolicies.yaml
  version/version.go
Labels: approved, do-not-merge/work-in-progress, lgtm
