Repository openshift-knative/knative-kafka-operator, pull requests merged in 2020-01, with the labels that each got.

#41 Adding Ali to this group
  OWNERS
Labels: approved, do-not-merge/invalid-owners-file, lgtm, size/XS

#43 Adding a some required network policy for openshift
  deploy/resources/networkpolicies.yaml
Labels: approved, lgtm, size/S

#42 Preparation for latest 0.11.x version
  deploy/olm-catalog/knative-kafka-operator/0.11.2/eventing_v1alpha1_knativeeventingkafka_crd.yaml
  deploy/olm-catalog/knative-kafka-operator/0.11.2/knative-kafka-operator.v0.11.2.clusterserviceversion.yaml
  deploy/olm-catalog/knative-kafka-operator/knative-kafka-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/kafka-channel-v0.10.0.yaml
  deploy/resources/kafka-channel-v0.11.2.yaml
  deploy/resources/kafka-source-v0.11.2.yaml
  version/version.go
Labels: approved, lgtm, size/XXL

#44 Adding produized image release yaml, and required NetworkPolicy
  deploy/olm-catalog/knative-kafka-operator/0.11.2/knative-kafka-operator.v0.11.2.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#45 Updates for 0.12.1
  README.md
  deploy/olm-catalog/knative-kafka-operator/0.12.1/eventing_v1alpha1_knativeeventingkafka_crd.yaml
  deploy/olm-catalog/knative-kafka-operator/0.12.1/knative-kafka-operator.v0.12.1.clusterserviceversion.yaml
  deploy/olm-catalog/knative-kafka-operator/knative-kafka-operator.package.yaml
  deploy/operator.yaml
  deploy/resources/kafka-channel-v0.11.2.yaml
  deploy/resources/kafka-channel-v0.12.1.yaml
  deploy/resources/kafka-source-v0.12.1.yaml
  version/version.go
Labels: approved, size/XXL
